Feat: WIP add createCollection
Ashe-Oro-Accelerator/hedera-nft-sdk pull request #12
Opened 2024-01-19 14:57 UTC by StanislawMazowieckiAriane

**Description**:

**Related issue(s)**:

Fixes #

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-22 09:09 UTC, BartoszSolkaArianelabs commented on src/functions/createCollection.ts
> +  if (!client) throw new Error('client is required');
please move all string messages to a dictionary file

2024-01-22 10:03 UTC, BartoszSolkaArianelabs commented on test/unit/createCollection.test.ts
> +    const treasuryAccount = '0.0.1234';
maybe let's not use the same AccountId as both treasuryAccount and expected value from createCollectionFunction? Just to avoid confustion

2024-01-22 10:03 UTC, BartoszSolkaArianelabs commented on test/unit/createCollection.test.ts
> +    ).rejects.toThrow();
can we assert that the correct message is returned?

2024-01-22 10:03 UTC, BartoszSolkaArianelabs commented on test/unit/createCollection.test.ts
> +    ).rejects.toThrow();
can we assert that the correct message is returned?

2024-01-22 10:03 UTC, BartoszSolkaArianelabs commented on test/unit/logIn.test.ts
> +    expect(() => logIn({ myAccountId: '', myPrivateKey })).toThrow();
can we assert that the correct message is returned?

2024-01-22 10:03 UTC, BartoszSolkaArianelabs commented on test/unit/logIn.test.ts
> +    expect(() => logIn({ myAccountId, myPrivateKey: '' })).toThrow();
can we assert that the correct message is returned?

2024-01-22 10:08 UTC, StanislawMazowieckiAriane commented on src/functions/createCollection.ts
> +  if (!client) throw new Error('client is required');
Done

2024-01-22 11:55 UTC, StanislawMazowieckiAriane commented on test/unit/createCollection.test.ts
> +    ).rejects.toThrow();
Done

2024-01-22 11:55 UTC, StanislawMazowieckiAriane commented on test/unit/createCollection.test.ts
> +    ).rejects.toThrow();
Done

2024-01-22 11:56 UTC, StanislawMazowieckiAriane commented on test/unit/logIn.test.ts
> +    expect(() => logIn({ myAccountId, myPrivateKey: '' })).toThrow();
Done

2024-01-24 11:34 UTC, michalrozekariane requested changes

2024-01-24 11:34 UTC, michalrozekariane commented on src/types/createCollection.ts
> +export type CreateCollectionKeys = {
Let's follow the convention to always use type / interface word at the end of every type & interface names.

2024-01-24 11:34 UTC, michalrozekariane commented on test/e2e/createCollectionE2E.test.ts
> +}
I think it would be better to move `getTokenInfo` func to utils/hedera/ and import it here

2024-01-24 11:34 UTC, michalrozekariane commented on test/unit/createCollection.test.ts
> +  it('should throw and error when only treasuryAccount is passed', async () => {
type: throw `an` error instead of `and`

2024-01-24 11:34 UTC, michalrozekariane commented on test/unit/createCollection.test.ts
> +  it('should throw and error when only treasuryAccountPrivateKey is passed', async () => {
type: throw `an` error instead of `and`

2024-01-24 11:34 UTC, michalrozekariane commented on test/unit/logIn.test.ts
> +jest.mock('@hashgraph/sdk', () => {
missing space

2024-01-24 11:34 UTC, michalrozekariane commented on test/__mocks__/consts.ts
> +import { HederaNFTSDK } from "../../src/HederaNFTSDK";
'HederaNFTSDK' is declared but its value is never read.

2024-01-24 11:54 UTC, michalrozekariane approved these changes

2024-01-24 11:55 UTC, merged