15 as a user i want to mint shared metadata nfts into a collection
Ashe-Oro-Accelerator/hedera-nft-sdk pull request #21
Opened 2024-01-25 15:35 UTC by StanislawMazowieckiAriane

**Related issue(s)**:

Fixes #

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-26 08:44 UTC, BartoszSolkaArianelabs commented on src/dictionary/errors.json
> +  "maxBuffer": "Max Buffer exceeded. Use buffer smaller than 10",
smaller or equal to 10

2024-01-26 08:45 UTC, BartoszSolkaArianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +  if (!supplyKey) throw new Error(errors.supplyKeyRequired);
supply key should be optional.

In the simplest token, a supply key is the same as the client key

2024-01-26 08:47 UTC, BartoszSolkaArianelabs commented on test/unit/mintSharedMetadataFunction.test.ts
> +  it('should handle error when buffer is higher than 10', async () => {
what is the difference between this one and `should handle error when buffer is bigger than 10`?

2024-01-26 09:09 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +  if (!supplyKey) throw new Error(errors.supplyKeyRequired);
This could be extracted to a separate function as the same validation will probably be in a ` mintUniqueMetadataFunction` also the code will be cleaner.

2024-01-26 09:11 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +  const numberOfCalls = Math.ceil(amount / buffer);
Add comment, explaining the formula

2024-01-26 09:13 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +  buffer,
This should be renamed to batchSize

2024-01-26 09:13 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +  if (buffer > 10) throw new Error(errors.maxBuffer);
Should be >=

2024-01-26 09:13 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +  if (buffer < 1) throw new Error(errors.minBuffer);
should be <= 1

2024-01-26 09:14 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +      const optionsHelper = new Array(Math.min(buffer, amount)).fill(metaData);
Can it be renamed to something more descriptive?

2024-01-26 09:18 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +    return successMetadata.flat(1);
isn't default value for flat `1`?

2024-01-26 09:18 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +    throw new Error(`${errors.mintingError} ${successMetadata.flat(1).join(' ')}`);
isn't default value for flat `1`?

2024-01-26 09:22 UTC, se7enarianelabs commented on src/functions/tokenMinter.ts
> +  supplyKey: string,
Why isn't it a PrivateKey type?

2024-01-26 09:23 UTC, se7enarianelabs commented on src/functions/tokenMinter.ts
> +    .setMaxTransactionFee(new Hbar(20))
`new Hbar(20)` is a magic number, maybe create a const

2024-01-26 09:24 UTC, se7enarianelabs commented on src/index.ts
> -  const tokenId = await nftSDK.createCollection('test', 'test2');
What is this file for?

2024-01-26 09:25 UTC, se7enarianelabs commented on src/index.ts
> +  // const tokenId = await nftSDK.createCollection('test', 'test2');
Why is this line commented?

2024-01-26 09:25 UTC, se7enarianelabs commented on src/types/mintToken.ts
> +  buffer: number;
maybe rename to batchSize?

2024-01-26 09:26 UTC, se7enarianelabs commented on test/unit/mintSharedMetadataFunction.test.ts
> +describe('mintUniqueMetadataFunction', () => {
typo, mintShared

2024-01-26 09:27 UTC, se7enarianelabs commented on test/unit/mintSharedMetadataFunction.test.ts
> +  it('should handle amount less than buffer correctly', async () => {
You should also test the edge values for Buffer so 1 and 10

2024-01-26 12:02 UTC, StanislawMazowieckiAriane commented on src/functions/mintSharedMetadataFunction.ts
> +  if (buffer < 1) throw new Error(errors.minBuffer);
Are you sure that the buffer can't be equal to 1?

2024-01-26 12:03 UTC, StanislawMazowieckiAriane commented on src/index.ts
> -  const tokenId = await nftSDK.createCollection('test', 'test2');
Now for tests in dev.
Later there would be export

2024-01-26 12:36 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +  if (buffer < 1) throw new Error(errors.minBuffer);
You are right, my mistake

2024-01-26 13:43 UTC, se7enarianelabs commented on src/index.ts
> -  const tokenId = await nftSDK.createCollection('test', 'test2');
I don't think this file should be committed, what do you think @BartoszSolkaArianelabs

2024-01-26 13:48 UTC, BartoszSolkaArianelabs commented on src/index.ts
> +  // const tokenId = await nftSDK.createCollection('test', 'test2');
IMO index.ts should not be the place to test the code. We have end2end tests for it

2024-01-26 13:48 UTC, BartoszSolkaArianelabs commented on src/index.ts
> -  const tokenId = await nftSDK.createCollection('test', 'test2');
IMO index.ts should not be the place to test the code. We have end2end tests for it

2024-01-30 14:55 UTC, StanislawMazowieckiAriane commented on test/unit/mintSharedMetadataFunction.test.ts
> +  it('should handle error when buffer is higher than 10', async () => {
done

2024-01-31 15:05 UTC, BartoszSolkaBD requested changes

2024-01-31 15:05 UTC, BartoszSolkaBD commented on test/e2e/mintSharedMetadataFunctionE2E.test.ts
> +    expect(transactionStatus).toEqual(['www.youtube.com']);
this test should also check if tokens are created on hedera network

2024-01-31 15:05 UTC, BartoszSolkaBD commented on test/e2e/mintSharedMetadataFunctionE2E.test.ts
> +    expect(transactionStatus).toEqual([
this test should also check if tokens are created on hedera network

2024-01-31 15:05 UTC, BartoszSolkaBD commented on test/e2e/mintSharedMetadataFunctionE2E.test.ts
> +    expect(transactionStatus).toBeDefined();
this test should also check if tokens are created on hedera network

2024-01-31 15:05 UTC, BartoszSolkaBD commented on test/e2e/mintSharedMetadataFunctionE2E.test.ts
> +  it('throws an error when invalid token ID is provided', async () => {
this has a wrong name

2024-01-31 15:05 UTC, BartoszSolkaBD commented on test/e2e/mintSharedMetadataFunctionE2E.test.ts
> +  it('throws an error when invalid token ID is provided', async () => {
this should be a unit test as it does not interact with any external components. Just checking if the validation works fine

2024-01-31 15:05 UTC, BartoszSolkaBD commented on test/unit/mintSharedMetadataFunction.test.ts
> +  it('should handle error when batchSize is lower than 0', async () => {
batch size in this test is not lower than 0, it's exactly 0.

2024-01-31 15:05 UTC, BartoszSolkaBD commented on test/unit/mintSharedMetadataFunction.test.ts
> +  it('should handle error when amount is not passed', async () => {
amount is passed, it's 0

2024-01-31 15:17 UTC, se7enarianelabs requested changes

2024-01-31 15:17 UTC, se7enarianelabs commented on test/unit/mintSharedMetadataFunction.test.ts
> +    expect(result).toEqual(expect.arrayContaining([mockMetaData]));
Cannot you monitor how many times tokenMinter was executed?

2024-01-31 19:27 UTC, se7enarianelabs requested changes

2024-01-31 19:27 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +    throw new Error(`${errors.mintingError} ${mintedMetadata.flat().join(' ')}`);
@StanislawMazowieckiAriane, 
will the developer easily catch this error and retrieve the list of metadata that were omitted? I am not familiar with this syntax: new Error(${errors.mintingError} ${mintedMetadata.flat().join(' ')})?

2024-01-31 19:27 UTC, se7enarianelabs commented on src/functions/mintSharedMetadataFunction.ts
> +  const mintedMetadata = [];
Rename it, as it no longer contains just the metadata but minted NFT data. Consider renaming it to something like 'mintedNFTs'

2024-01-31 23:26 UTC, StanislawMazowieckiAriane commented on src/functions/mintSharedMetadataFunction.ts
> +    throw new Error(`${errors.mintingError} ${mintedMetadata.flat().join(' ')}`);
Yes.
Example: 
Error: There was an error while minting the NFT. Successfully minted:  [{"content":"www.google.com","serialNumber":866},{"content":"www.google.com","serialNumber":867},{"content":"www.google.com","serialNumber":868},{"content":"www.google.com","serialNumber":869},{"content":"www.google.com","serialNumber":870}]

2024-02-01 10:01 UTC, se7enarianelabs approved these changes

2024-02-01 10:14 UTC, merged