14-as-a-user-i-want-to-create-hip-412-compliant-json-files-from-csv
Ashe-Oro-Accelerator/hedera-nft-sdk pull request #22
Opened 2024-01-29 10:56 UTC by michalrozekariane

**Related issue(s)**:

#14 

**Checklist**

2024-01-29 14:32 UTC, se7enarianelabs requested changes

2024-01-29 14:32 UTC, se7enarianelabs commented on metadata-example-attributes-and-properties.csv
> +name,creator,creatorDID,description,image,type,properties,,attributes,,
Should this file be in the root directory?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +  static AMOUNT_OF_HEADERS = 2;
why is one variable in lower case and the other in upper case?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +    if (!!process.env?.CSV_SEPARATOR && process.env?.CSV_SEPARATOR === 'semicolon') {
Maybe extract 'semicolon' to a const

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +
why is here a blank line?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +
why is here a blank line?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +    }
This could be extracted to a separate function

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +            }
This could be extracted to a separate function

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +      return rows;
Is this return necessary?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +      if (header.header === this.properties) {
else if?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +      if (!currentType) {
else if?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +        header.header !== this.properties
Can you simplify it? Looking at the if statements above?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +        refToErrorArray.push(dictionary.csvToJson.errorInCellWithHeader(1, header.index + 1));
Magic 1? Why is it 1? Maybe extract it to a variable?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +        refToErrorArray.push(dictionary.csvToJson.errorInCellWithHeader(1, header.index + 1));
Magic 1? Why is it 1? Maybe extract it to a variable?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +    return (header: { header: string; index: number }): string | null => {
This return can be extracted to a separate function, additionally maybe it is possible to reduce the number of if statements?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/functions/createCollection.ts
>      (!treasuryAccount && treasuryAccountPrivateKey)
What does the if statement validate?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/functions/createJsonMetadataFromCsv.ts
> +import forEach from 'lodash/forEach';
Is this import necessary?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/functions/createJsonMetadataFromCsv.ts
> +  const noAttributesRowsLocations = objectsFromCsvRows.reduce<string[]>((acc, row, index) => {
what is `acc`?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/index.ts
> +// import axios from 'axios'
Don't commit commented lines

2024-01-29 14:32 UTC, se7enarianelabs commented on src/utils/services/csvTransformer.ts
> +    const OMITTED_HEADER = 1;
Maybe: `OMITTED_HEADER_COUNT`

2024-01-29 14:32 UTC, se7enarianelabs commented on src/utils/services/csvTransformer.ts
> +        return csvRowAsObject;
maybe extract to a function?

2024-01-29 14:32 UTC, se7enarianelabs commented on src/utils/validation-schemas/hip412Metadata.schema.ts
> +  description: z.string().min(1),
Check this, because description is not required?

2024-01-29 14:38 UTC, se7enarianelabs commented on src/utils/validation-schemas/hip412Metadata.schema.ts
> +  description: z.string().min(1),
From docs: `The description field is optional, but recommended to enable apps to display them better.`

2024-01-31 10:20 UTC, michalrozekariane commented on metadata-example-attributes-and-properties.csv
> +name,creator,creatorDID,description,image,type,properties,,attributes,,
done

2024-01-31 10:29 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +  static AMOUNT_OF_HEADERS = 2;
done

2024-01-31 10:34 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +    if (!!process.env?.CSV_SEPARATOR && process.env?.CSV_SEPARATOR === 'semicolon') {
done

2024-01-31 10:34 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +
done

2024-01-31 10:34 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +
done

2024-01-31 10:36 UTC, michalrozekariane commented on src/functions/createJsonMetadataFromCsv.ts
> +  const noAttributesRowsLocations = objectsFromCsvRows.reduce<string[]>((acc, row, index) => {
It's shortcut from "accumulator" which is the first argument of `reduce` func

2024-01-31 10:39 UTC, michalrozekariane commented on src/index.ts
> +// import axios from 'axios'
done

2024-01-31 10:40 UTC, michalrozekariane commented on src/utils/services/csvTransformer.ts
> +    const OMITTED_HEADER = 1;
done

2024-01-31 10:41 UTC, michalrozekariane commented on src/utils/validation-schemas/hip412Metadata.schema.ts
> +  description: z.string().min(1),
done

2024-01-31 11:22 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +    }
done

2024-01-31 11:37 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +            }
done

2024-01-31 11:42 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +      if (header.header === this.properties) {
done

2024-01-31 11:47 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +      if (!currentType) {
done

2024-01-31 13:43 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +        header.header !== this.properties
done

2024-01-31 13:45 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +        refToErrorArray.push(dictionary.csvToJson.errorInCellWithHeader(1, header.index + 1));
done

2024-01-31 13:46 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +        refToErrorArray.push(dictionary.csvToJson.errorInCellWithHeader(1, header.index + 1));
done

2024-01-31 15:10 UTC, michalrozekariane commented on src/functions/createCollection.ts
>      (!treasuryAccount && treasuryAccountPrivateKey)
this is not part if this PR

2024-01-31 15:12 UTC, michalrozekariane commented on src/functions/createJsonMetadataFromCsv.ts
> +import forEach from 'lodash/forEach';
it's because it's used in mintbox

2024-01-31 15:29 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +    return (header: { header: string; index: number }): string | null => {
done

2024-01-31 15:53 UTC, michalrozekariane commented on src/utils/services/csvTransformer.ts
> +        return csvRowAsObject;
done

2024-01-31 19:40 UTC, se7enarianelabs requested changes

2024-01-31 19:40 UTC, se7enarianelabs commented on metadata-example-attributes-and-properties.csv
> +name,creator,creatorDID,description,image,type,properties,,attributes,,
Why is it in the root directory?

2024-01-31 19:40 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +  static AMOUNT_OF_HEADERS = 2;
Nothing changed?

2024-01-31 19:40 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +const EXTRA_SECOND_HEADER_ROW_COUNT = 1;
Strange name

2024-01-31 19:40 UTC, se7enarianelabs commented on src/CsvFileReader.ts
> +      if (e instanceof CSVReaderError) {
Why only `e instanceof CSVReaderError` should thorw an error?

2024-01-31 19:40 UTC, se7enarianelabs commented on test/integration/createJsonMetadataFromCsv.test.ts
> +  const jsonMetadataOutputFolderPath = 'test/integration/output';
This could be extracted to a config file

2024-01-31 19:40 UTC, se7enarianelabs commented on test/integration/createJsonMetadataFromCsv.test.ts
> +    const csvFilePath = 'test/__mocks__/csvExampleWithImages.csv';
This path could be a const, maybe even in a test config file?

2024-01-31 19:40 UTC, se7enarianelabs commented on test/integration/createJsonMetadataFromCsv.test.ts
> +  }, 10000);
`10000` should be a const, maybe even in somekind of a config file

2024-01-31 19:40 UTC, se7enarianelabs commented on test/integration/createJsonMetadataFromCsv.test.ts
> +    const csvFilePath = 'test/__mocks__/csvExampleWithImages.csv';
same as above

2024-01-31 19:40 UTC, se7enarianelabs commented on test/integration/createJsonMetadataFromCsv.test.ts
> +    const csvFilePath = 'test/__mocks__/csvExampleOnlyRequiredFields.csv';
same as above

2024-01-31 19:40 UTC, se7enarianelabs commented on test/integration/createJsonMetadataFromCsv.test.ts
> +    const csvFilePath = 'test/__mocks__/csvExampleWithMissingRequiredFields.csv';
same as above

2024-02-01 10:23 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +const EXTRA_SECOND_HEADER_ROW_COUNT = 1;
done

2024-02-01 10:28 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +      if (e instanceof CSVReaderError) {
It's mintbox code

2024-02-01 10:33 UTC, michalrozekariane commented on test/integration/createJsonMetadataFromCsv.test.ts
> +  const jsonMetadataOutputFolderPath = 'test/integration/output';
done

2024-02-01 10:34 UTC, michalrozekariane commented on test/integration/createJsonMetadataFromCsv.test.ts
> +    const csvFilePath = 'test/__mocks__/csvExampleWithImages.csv';
done

2024-02-01 10:36 UTC, michalrozekariane commented on test/integration/createJsonMetadataFromCsv.test.ts
> +  }, 10000);
done

2024-02-01 10:36 UTC, michalrozekariane commented on test/integration/createJsonMetadataFromCsv.test.ts
> +    const csvFilePath = 'test/__mocks__/csvExampleWithImages.csv';
done

2024-02-01 10:36 UTC, michalrozekariane commented on test/integration/createJsonMetadataFromCsv.test.ts
> +    const csvFilePath = 'test/__mocks__/csvExampleOnlyRequiredFields.csv';
done

2024-02-01 10:36 UTC, michalrozekariane commented on test/integration/createJsonMetadataFromCsv.test.ts
> +    const csvFilePath = 'test/__mocks__/csvExampleWithMissingRequiredFields.csv';
done

2024-02-02 11:23 UTC, BartoszSolkaArianelabs commented on src/CsvFileReader.ts
> +      if (e instanceof CSVReaderError) {
please add a comment in the code explaining this

2024-02-02 11:31 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +      if (e instanceof CSVReaderError) {
done

2024-02-02 13:05 UTC, se7enarianelabs requested changes

2024-02-02 14:31 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +    if (currentType === 'properties') {
done

2024-02-02 14:31 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +    if (currentType === 'attributes') {
done

2024-02-02 14:32 UTC, michalrozekariane commented on src/CsvFileReader.ts
> +    fullPath: string,
done

2024-02-02 19:03 UTC, michalrozekariane commented on src/functions/createJsonMetadataFromCsv.ts
> +export const createJsonMetadataFromCsv = async ({
done

2024-02-05 09:26 UTC, michalrozekariane commented on src/CSVFileReader.ts
> +    if (currentType === 'properties') {
done

2024-02-05 09:26 UTC, michalrozekariane commented on src/CSVFileReader.ts
> +    if (currentType === 'attributes') {
done

2024-02-05 09:31 UTC, se7enarianelabs approved these changes

2024-02-06 09:51 UTC, StanislawMazowieckiAriane approved these changes

2024-02-06 09:52 UTC, merged