20 as a user i want to mint unique metadata nfts into a collection
Ashe-Oro-Accelerator/hedera-nft-sdk pull request #23
Opened 2024-01-30 13:38 UTC by StanislawMazowieckiAriane

**Description**:

**Related issue(s)**:

Fixes #

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-02-01 11:37 UTC, BartoszSolkaArianelabs requested changes

2024-02-01 11:37 UTC, BartoszSolkaArianelabs commented on src/functions/mintUniqueMetadataFunction.ts
> +        }
this can be extracted to a separate function

2024-02-01 11:37 UTC, BartoszSolkaArianelabs commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +  }, 25000);
please extract this to a const that will be used by all the tests

2024-02-01 11:37 UTC, BartoszSolkaArianelabs commented on test/unit/mintUniqueMetadataFunction.test.ts
> +          handler({ '0': 123 });
So if I would like my metadata CSV to be a file like
```
1
2
3
4
```
Does it throw an error?
@se7enarianelabs should this be the intended behaviour?

2024-02-01 12:04 UTC, se7enarianelabs requested changes

2024-02-01 12:04 UTC, se7enarianelabs commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +      'test/__mocks__/testOneLine.csv',
Extract this to a some config file as this is a constant path for the whole SDK

2024-02-01 12:04 UTC, se7enarianelabs commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +  }, 25000);
extract to a const

2024-02-01 12:04 UTC, se7enarianelabs commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +      'test/__mocks__/testRows.csv',
same as above

2024-02-01 12:04 UTC, se7enarianelabs commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +        'test/__mocks__/testRows.csv',
same as above

2024-02-01 12:04 UTC, se7enarianelabs commented on test/unit/mintUniqueMetadataFunction.test.ts
> +          handler({ '0': 123 });
The file example that you provided is a valid one, and it shouldn't throw an error

2024-02-01 12:10 UTC, StanislawMazowieckiAriane commented on src/functions/mintUniqueMetadataFunction.ts
> +  pathToCSV,
done

2024-02-01 12:10 UTC, StanislawMazowieckiAriane commented on src/functions/mintUniqueMetadataFunction.ts
> +        }
Done. Yes

2024-02-01 12:10 UTC, StanislawMazowieckiAriane commented on src/HederaNFTSDK.ts
> +    pathToCSV: string,
Done

2024-02-01 12:11 UTC, StanislawMazowieckiAriane commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +  }, 25000);
Done

2024-02-01 12:11 UTC, StanislawMazowieckiAriane commented on src/functions/mintUniqueMetadataFunction.ts
> +    throw new Error(`${errors.mintingError} ${successMetadata.flat(1).join(' ')}`);
Done

2024-02-01 12:11 UTC, StanislawMazowieckiAriane commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +  }, 25000);
Done

2024-02-01 12:18 UTC, StanislawMazowieckiAriane commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +        'test/__mocks__/testRows.csv',
Done

2024-02-01 12:18 UTC, StanislawMazowieckiAriane commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +      'test/__mocks__/testRows.csv',
Done

2024-02-01 12:18 UTC, StanislawMazowieckiAriane commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +      'test/__mocks__/testOneLine.csv',
Done

2024-02-01 13:05 UTC, StanislawMazowieckiAriane commented on test/unit/mintUniqueMetadataFunction.test.ts
> +          handler({ '0': 123 });
Done

2024-02-01 14:20 UTC, StanislawMazowieckiAriane commented on src/functions/mintUniqueMetadataFunction.ts
> +  return mintedNFTs.flat(1);
Done

2024-02-01 14:23 UTC, StanislawMazowieckiAriane commented on test/e2e/createCollectionE2E.test.ts
> +  }, 10000);
Done

2024-02-01 14:23 UTC, StanislawMazowieckiAriane commented on src/index.ts
> +    metadata: [
Done

2024-02-01 16:00 UTC, se7enarianelabs approved these changes

2024-02-02 08:54 UTC, BartoszSolkaArianelabs commented on src/utils/validateProps.ts
> +    throw new Error(errors.csvOrArrayRequired);
each of these validations could be extracted to a separate function

example:
```js
function validateMinBatchSize(batchSize: number | null) {
  if (batchSize !== null && batchSize < 1) throw new Error(errors.minBatchSize);
}

function validateMaxBatchSize(batchSize: number | null) {
  if (batchSize !== null && batchSize > 10) throw new Error(errors.maxBatchSize);
}
```

2024-02-02 08:55 UTC, BartoszSolkaArianelabs commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +});
this can be removed

2024-02-02 08:59 UTC, BartoszSolkaArianelabs commented on src/functions/mintUniqueMetadataFunction.ts
> +  }
this could be extracted to a separate function `mintNFTs`

2024-02-02 08:59 UTC, BartoszSolkaArianelabs commented on src/functions/mintUniqueMetadataFunction.ts
> +    : metadataArray || [];
this can be extracted to a separate function `getMetadata`

2024-02-02 09:01 UTC, BartoszSolkaArianelabs commented on src/functions/mintToken.ts
> +  if (CIDs.some((cid) => cid.toString().length > 100)) {
As max size is 100, please write tests for metadata with:
- 99 chars
- 100 chars
- 101 chars

99 and 100 should pass, when 101 should fail

2024-02-02 09:55 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +    throw new Error(errors.csvOrArrayRequired);
??? Check again what is this function doing. I can't call each separate function to check props. I call once function pass it props and it should check if pros are well passed

2024-02-02 09:56 UTC, StanislawMazowieckiAriane commented on test/e2e/mintUniqueMetadataFunctionE2E.test.ts
> +});
Done

2024-02-02 10:02 UTC, StanislawMazowieckiAriane commented on src/functions/mintUniqueMetadataFunction.ts
> +    : metadataArray || [];
Same as above

2024-02-02 10:11 UTC, BartoszSolkaArianelabs commented on src/utils/validateProps.ts
> +    throw new Error(errors.csvOrArrayRequired);
I meant something like

```typescript
export const validateProps = ({
  ...
}: {
  ...
}) => {
  validateMaxBatchSize(batchSize);
  validateMinBatchSize(batchSize);
  ...
};

function validateMinBatchSize(batchSize: number | null) {
  if (batchSize !== null && batchSize < 1) throw new Error(errors.minBatchSize);
}

function validateMaxBatchSize(batchSize: number | null) {
  if (batchSize !== null && batchSize > 10) throw new Error(errors.maxBatchSize);
}
```

2024-02-02 13:57 UTC, StanislawMazowieckiAriane commented on src/functions/mintToken.ts
> +  if (CIDs.some((cid) => cid.toString().length > 100)) {
Done

2024-02-02 14:35 UTC, se7enarianelabs requested changes

2024-02-02 14:35 UTC, se7enarianelabs commented on src/utils/validateProps.ts
> +};
I don't like the idea of isUnique, it's better to have two functions:

```
validateBasicProps = (props: PropsType) => {
  validateSupplyKey(props);
  validateBatchSize(props);
  validateTokenId(props);
  validateAmount(props);
  validateMetaData(props);
  validateMetadataArray(props);
  validatePathToMetadataURIsFile(props);
};

validatePropsForUniqueNFTMinting = (props: PropsType) => {
  validateBasicProps()
  //TO DO cafunction for validation specific for the unique case

};

```

2024-02-02 14:35 UTC, se7enarianelabs commented on src/utils/validateProps.ts
> +const validateSupplyKey = (props: PropsType) => {
Why does this function take: `PropsType` as parameter when it only uses one field from it?

2024-02-02 14:35 UTC, se7enarianelabs commented on src/utils/validateProps.ts
> +const validateBatchSize = (props: PropsType) => {
Why does this function take: `PropsType` as parameter when it only uses one field from it?

2024-02-02 14:35 UTC, se7enarianelabs commented on src/utils/validateProps.ts
> +  if (Object.prototype.hasOwnProperty.call(props, 'supplyKey')) {
Why do you need this line? Cannot you just check it like this: 
`  if (supplyKey !== null && !supplyKey) throw new Error(errors.supplyKeyRequired);`

2024-02-02 14:35 UTC, se7enarianelabs commented on src/utils/validateProps.ts
> +  if (Object.prototype.hasOwnProperty.call(props, 'batchSize')) {
same as above

2024-02-02 14:35 UTC, se7enarianelabs commented on src/utils/validateProps.ts
> +const validateTokenId = (props: PropsType) => {
Why does this function take: PropsType as parameter when it only uses one field from it?

2024-02-02 14:35 UTC, se7enarianelabs commented on src/utils/validateProps.ts
> +    ) {
Same as above

2024-02-02 15:08 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +    throw new Error(errors.csvOrArrayRequired);
done

2024-02-02 15:36 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +const validateSupplyKey = (props: PropsType) => {
It takes all props with the type PropsType. It needs to take all because I'm looking for usage in first if inside all functions

2024-02-02 15:40 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +const validateSupplyKey = (props: PropsType) => {
It's not using only one fileld. Check first if inside this function. It's looking for a call on all props object

2024-02-02 15:40 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +const validateBatchSize = (props: PropsType) => {
above

2024-02-02 15:58 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +  if (Object.prototype.hasOwnProperty.call(props, 'supplyKey')) {
Nope. I want this function as generic as it can be. 

The Object.prototype.hasOwnProperty.call(props, 'batchSize') is used to check if the props object has a property named batchSize. This method will return true even if the value of the property is null or undefined.  

On the other hand, props.batchSize !== null only checks if the batchSize property is not null. It doesn't check if the props object actually has a batchSize property. Also, it will return true if batchSize is undefined.  

So, Object.prototype.hasOwnProperty.call(props, 'batchSize') is a more thorough check because it ensures that the batchSize property exists on the props object, regardless of its value.

For example without this line, this test would be successful which is not supposed to:

  it('should throw an error if supplyKey is not provided', () => {
    expect(() => validateProps({ supplyKey: undefined })).toThrow(errors.supplyKeyRequired);
  });

2024-02-02 16:02 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +  if (Object.prototype.hasOwnProperty.call(props, 'batchSize')) {
above

2024-02-02 16:02 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +const validateTokenId = (props: PropsType) => {
above

2024-02-02 16:02 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +    ) {
above

2024-02-02 16:08 UTC, StanislawMazowieckiAriane commented on src/utils/validateProps.ts
> +};
Done

2024-02-05 08:45 UTC, BartoszSolkaArianelabs approved these changes

2024-02-06 09:19 UTC, se7enarianelabs requested changes
Remove isUnique and you it will be approved by me

2024-02-06 09:54 UTC, michalrozekariane commented on test/__mocks__/testOneLine.csv
> +https://www.youtube.com1,https://www.youtube.com2
Can you put all your `.csv` files inside csv folder? This will be consistent with what I did on branch 14

2024-02-06 10:33 UTC, se7enarianelabs approved these changes

2024-02-06 14:54 UTC, se7enarianelabs requested changes

2024-02-06 14:54 UTC, se7enarianelabs commented on src/types/validateProps.ts
> +export type validateUniqueProps = {
This name sounds like a function, rename to something like `uniqueMintingValidationProps`

2024-02-06 21:46 UTC, StanislawMazowieckiAriane commented on src/types/validateProps.ts
> +export type validateUniqueProps = {
done

2024-02-07 09:00 UTC, se7enarianelabs approved these changes

2024-02-07 10:10 UTC, StanislawMazowieckiAriane commented on test/__mocks__/testOneLine.csv
> +https://www.youtube.com1,https://www.youtube.com2
done

2024-02-07 10:13 UTC, merged