26-as-a-user-i-want-to-validate-if-metadata-is-hip-412-compliant
Ashe-Oro-Accelerator/hedera-nft-sdk pull request #30
Opened 2024-02-11 19:19 UTC by michalrozekariane

**Description**:

**Related issue(s)**:

Fixes #26 

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-02-13 09:42 UTC, BartoszSolkaArianelabs requested changes

2024-02-13 09:42 UTC, BartoszSolkaArianelabs commented on src/utils/services/Hip412Validator.ts
> +      });
why is it required to sort the files?

2024-02-13 09:42 UTC, BartoszSolkaArianelabs commented on test/unit/validateSingleMetadataObject.test.ts
> +});
please add a test for validating object with multiple errors

2024-02-13 11:04 UTC, BartoszSolkaArianelabs requested changes

2024-02-16 09:38 UTC, michalrozekariane commented on src/utils/services/Hip412Validator.ts
> +      .filter((file) => file !== '.gitkeep')
done

2024-02-16 13:22 UTC, michalrozekariane commented on test/unit/validateSingleMetadataObject.test.ts
> +});
done

2024-02-19 10:35 UTC, se7enarianelabs requested changes

2024-02-19 10:35 UTC, se7enarianelabs commented on src/api/mirrorNode.ts
> +      error: errorMessage,
Wouldn't it be good if it would also return a status if successful or failed?

2024-02-19 10:35 UTC, se7enarianelabs commented on src/types/nfts.ts
> +  meta?: NFTMetadata;
Why meta and not metadata?

2024-02-19 10:35 UTC, se7enarianelabs commented on src/utils/helpers/nftMetadataDecoder.ts
> +    let decodedNFTMetadata: string;
Initialize it with a default value like "", it's a good practice

2024-02-19 10:35 UTC, se7enarianelabs commented on src/utils/helpers/nftMetadataDecoder.ts
> +export const nftMetadataDecoder = (
rename function to a URI decoder, as it does not decode the metadata,
I thought that it downloads/decodes the final metadata from the NFTs uri

2024-02-19 10:35 UTC, se7enarianelabs commented on src/utils/services/Hip412Validator.ts
> +              errorToMessage(e) === 'Required' ? dictionary.validation.requiredFieldMissing : e
extract `'Required'` to a const

2024-02-19 10:35 UTC, se7enarianelabs commented on src/utils/services/Hip412Validator.ts
> +        errors.push(
in validateSingleMetadataObject in the catch statement you check if the err is an instanceof ValidationError.
Here you don't do it, why?

2024-02-19 10:35 UTC, se7enarianelabs commented on src/utils/services/Hip412Validator.ts
> +    }
You could extract this fragment and use it in validateArrayOfObjects as well

2024-02-19 10:35 UTC, se7enarianelabs commented on src/utils/services/Hip412Validator.ts
> +      });
Why do we need this?

2024-02-20 08:13 UTC, michalrozekariane commented on src/api/mirrorNode.ts
> +    .get(`${url}/tokens/${nftId.tokenId.toString()}/nfts/${nftId.serial.toString()}`)
done

2024-02-20 08:14 UTC, michalrozekariane commented on src/api/mirrorNode.ts
> +  let nextLink: string = `${baseUrl}/tokens/${tokenId}/nfts`;
done

2024-02-20 09:28 UTC, michalrozekariane commented on src/utils/helpers/nftMetadataDecoder.ts
> +export const nftMetadataDecoder = (
done

2024-02-20 09:36 UTC, michalrozekariane commented on src/utils/services/Hip412Validator.ts
> +              errorToMessage(e) === 'Required' ? dictionary.validation.requiredFieldMissing : e
done

2024-02-20 11:22 UTC, michalrozekariane commented on src/utils/services/Hip412Validator.ts
> +      });
`file !== '.gitkeep'` deleted. Also I added a comment explaining what sorting is for.

2024-02-20 11:24 UTC, michalrozekariane commented on src/utils/services/Hip412Validator.ts
> +    }
as we discussed - the error structure is a little bit different for array

2024-02-20 11:24 UTC, michalrozekariane commented on src/utils/services/Hip412Validator.ts
> +        errors.push(
as we discussed - the error structure is a little bit different for array

2024-02-20 11:24 UTC, michalrozekariane commented on src/utils/helpers/nftMetadataDecoder.ts
> +    let decodedNFTMetadata: string;
done

2024-02-20 11:25 UTC, michalrozekariane commented on src/types/nfts.ts
> +  meta?: NFTMetadata;
`meta?` field deleted, it's not needed, good catch.

2024-02-20 11:27 UTC, michalrozekariane commented on src/api/mirrorNode.ts
> +      error: errorMessage,
done

2024-02-20 11:27 UTC, michalrozekariane commented on src/api/mirrorNode.ts
> +};
I will, thanks.

2024-02-21 09:28 UTC, se7enarianelabs approved these changes

2024-02-23 09:12 UTC, BartoszSolkaArianelabs commented
Merged in hedera-nft-utilities

2024-02-23 09:12 UTC, closed without merging